=== DusanBucan/XWS/xmlScientificPublicationEditor/src/main/resources/data/schemas/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.uns.ac.rs/Tim1"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://www.uns.ac.rs/Tim1" elementFormDefault="qualified" vc:minVersion="1.1">

    <xs:element name="person" type="TPerson"/>
    <xs:complexType name="TPerson">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="surname">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern
                            value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"
                        />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="phone">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{3}-[0-9]{6,7}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="institution" type="TInstitution"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="expertise" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="TInstitution">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="address" type="TAddress"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="TAddress">
        <xs:sequence>
            <xs:element name="city">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="streetNumber">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="floorNumber">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="[/+-]?[0-9]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="street">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="country">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== DusanBucan/XWS/DusanPerson.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns="http://www.uns.ac.rs/Tim1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uns.ac.rs/Tim1 file:/home/dusanb/Documents/Semestar7/XML_webServisi/projekat/XWS/person.xsd">
    <name>Dusan</name>
    <surname>Bucan</surname>
    <email>dusanbzr@gmail.com</email>
    <phone>063-2222222</phone>
    <institution id="dasdas">
        <name>FTN</name>
        <address>
            <city>Novi Sad</city>
            <street>neka leva</street>
            <country>Srbija</country>
        </address>
    </institution>
    <expertise>IT</expertise>
</person>
